version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
