# Generated by Django 5.1.2 on 2024-12-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_company_remove_subscription_service_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
    ]
