# Generated by Django 5.1.2 on 2024-12-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_subscription_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
